$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: my-deployment
endpoint_name: my-endpoint
model:
  name: model-registered
  version: 1
  path: azureml://subscriptions/${{ secrets.SUBSCRIPION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP }}/workspaces/${{ secrets.WORKSPACE_NAME }}/datastores/workspaceartifactstore/paths/ExperimentRun/dcid.shy_lion_7fz97zntk2/model
  type: mlflow_model
instance_type: Standard_DS3_v2
instance_count: 1
