$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: mslearn-mlops-my-deployment
endpoint_name: mslearn-mlops-my-online-endpoint
model: azureml://locations/westeurope/workspaces/cd57c70d-fd42-448a-be0f-ee1fd478b473/models/model-from-job-output-manually-registered/versions/1
instance_type: Standard_DS3_v2
instance_count: 1
