$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: mslearn-mlops-my-deployment
endpoint_name: mslearn-mlops-my-online-endpoint
model:
  name: model-from-job-output-manually-registered
  version: 1
  type: mlflow_model
instance_type: Standard_D2as_v4
instance_count: 3
