$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: my-deployment
endpoint_name: my-endpoint
model:
  name: model-registered
  version: 1
  type: mlflow_model
instance_type: Standard_DS3_v2
instance_count: 1
