name: GitHub Actions workflow triggered by the creation of a pull request + linting + Flake8

on:
  pull_request:
  merge_group:
    branches:
      - main

jobs:
  job1:
    name: linting flake8
    runs-on: ubuntu-latest

    steps:
    
      - name: Check out repo
        uses: actions/checkout@main
        
      - name: Use Pyhton version 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          
      - name: Install Flake8
        run: |
          python -m pip install flake8
          
      - name: Run linting tests
        run: |
          flake8 src/model/

  job2:
    name: Running Pytest
    runs-on: ubuntu-latest

    steps:
    
      - name: Check out repo
        uses: actions/checkout@main
        
      - name: Use Pyhton version 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install pip<24.1
        run: python -m pip install --upgrade "pip<24.1"
          
      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install -r requirements.txt

      - name: Run Pytest
        run: |
          pytest tests/
  
