name: Azure ML job to DEV and PROD env

on:
  push:
    branches:
      - main

jobs:
  job1:
    name: train model in dev env
    runs-on: ubuntu-latest
    environment:
      name: dev_env
    steps:
    
    - name: Check out repo
      uses: actions/checkout@main
      
    - name: Install az ml extension
      run: az extension add -n ml -y
      
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
      
    - name: Trigger Azure Machine Learning job
      run: |
       az ml job create --file src/job-dev.yml \
                        --resource-group ${{ secrets.RESOURCE_GROUP }} \
                        --workspace-name ${{ secrets.WORKSPACE_NAME }} \
                        --set compute=${{ secrets.COMPUTE_NAME }} \
                        --stream

  job2:
    name:  train model in prod env
    needs: job1
    runs-on: ubuntu-latest
    environment:
      name: prod_env
    steps:
    
    - name: Check out repo
      uses: actions/checkout@main
      
    - name: Install az ml extension
      run: az extension add -n ml -y
      
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
      
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/job-prod.yml \
                         --resource-group ${{ secrets.RESOURCE_GROUP }} \
                         --workspace-name ${{ secrets.WORKSPACE_NAME }} \
                         --set compute=${{ secrets.COMPUTE_NAME }} \
                         --stream
