name: Manually trigger an Azure Machine Learning job to dev env and prod env

on:
  push:
    branches:
      - main

jobs:
  job1:
    name: train the model in the dev environment using the diabetes-dev-folder dataset as input
    runs-on: ubuntu-latest
    environment:
      name: dev_env
    steps:
    
    - name: Check out repo
      uses: actions/checkout@main
      
    - name: Install az ml extension
      run: az extension add -n ml -y
      
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: set current directory
      run: cd src
      
    - name: Trigger Azure Machine Learning job
      run: |
       az ml job create --file src/job.yml --resource-group rg-for-mslearn-mlops --workspace-name ws-mslearn-mlops-dev --stream

  job2:
    name:  train the model in the prod environment, using the diabetes-prod-folder data asset as input
    needs: job1
    runs-on: ubuntu-latest
    environment:
      name: prod_env
    steps:
    
    - name: Check out repo
      uses: actions/checkout@main
      
    - name: Install az ml extension
      run: az extension add -n ml -y
      
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: set current directory
      run: cd src
      
    - name: Trigger Azure Machine Learning job
      run: |
       az ml job create --file src/job.yml --resource-group rg-for-mslearn-mlops --workspace-name ws-mslearn-mlops-prod --stream
