name: Create Endpoint and Deploy Model

on:
  workflow_dispatch:

jobs:
  deploy-model:
    runs-on: ubuntu-latest
    environment:
      name: prod_env

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@main

      # Step 2: Install the Azure ML CLI extension
      - name: Install az ml extension
        run: az extension add -n ml -y

      # Step 3: Azure login
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 5: Create a managed online endpoint
      - name: Create a managed online endpoint
        run: |
          # Check if endpoint exists and create or update accordingly
          if az ml online-endpoint show --name my-endpoint --resource-group ${{ secrets.RESOURCE_GROUP }} --workspace-name ${{ secrets.WORKSPACE_NAME }}; then
            az ml online-endpoint update --name my-endpoint -f endpoints/online/endpoint.yml --resource-group ${{ secrets.RESOURCE_GROUP }} --workspace-name ${{ secrets.WORKSPACE_NAME }}
          else
            az ml online-endpoint create --name my-endpoint -f endpoints/online/endpoint.yml --resource-group ${{ secrets.RESOURCE_GROUP }} --workspace-name ${{ secrets.WORKSPACE_NAME }}
          fi

          # Endpoint details
          echo "Endpoint details:"
          az ml online-endpoint show --name my-endpoint --resource-group ${{ secrets.RESOURCE_GROUP }} --workspace-name ${{ secrets.WORKSPACE_NAME }}

      # Step 6: Create the deployment
      - name: Create the deployment
        run: |
          # Log model details
          echo "Model details:"
          az ml model show --name model-registered --version 1 --resource-group ${{ secrets.RESOURCE_GROUP }} --workspace-name ${{ secrets.WORKSPACE_NAME }}

          # Create the deployment
          echo "Creating deployment..."
          az ml online-deployment create \
            --name my-deployment \
            --endpoint my-endpoint \
            -f endpoints/online/deployment.yml \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --workspace-name ${{ secrets.WORKSPACE_NAME }} \
            --all-traffic

          # Verify the deployment
          echo "Verifying the deployment..."
          az ml online-deployment show \
            --name my-deployment \
            --endpoint mslearn-mlops-my-online-endpointe \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --workspace-name ${{ secrets.WORKSPACE_NAME }}

      # Step 7: Invoke the endpoint
      - name: Invoke the endpoint
        run: |
          # Invoke the endpoint to validate deployment
          echo "Invoking the endpoint..."
          az ml online-endpoint invoke \
            --name my-endpoint \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --workspace-name ${{ secrets.WORKSPACE_NAME }} \
            --request-file endpoints/online/sample-request.json || { echo 'Endpoint invocation failed'; exit 1; }
