name: Deploy Model to Endpoint

on:
  push:
    branches:
      - main

jobs:
  deploy-model:
    runs-on: ubuntu-latest
    environment:
      name: prod_env

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@main

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install Azure ML CLI
      - name: Install Azure CLI and ML extension
        run: |
          pip install azure-ai-ml azure-identity

      # Step 4: Azure login
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      # Step 5: Deploy Model to Endpoint
      - name: Deploy Model
        run: |
          # Set variables
          resource_group="rg-for-mslearn-mlops"
          workspace_name="ws2-mslearn-mlops-prod" 
          endpoint_name="mslearn-mlops-my-online-endpoint"
          model_name="model-from-job-output-manually-registered"

          # Check if endpoint exists and create or update accordingly
          if az ml online-endpoint show --name $endpoint_name --resource-group $resource_group --workspace-name $workspace_name; then
            az ml online-endpoint update --name $endpoint_name -f endpoints/online/endpoint.yml --resource-group $resource_group --workspace-name $workspace_name
          else
            az ml online-endpoint create --name $endpoint_name -f endpoints/online/endpoint.yml --resource-group $resource_group --workspace-name $workspace_name
          fi

          # Deploy the latest model version to the endpoint
          az ml online-deployment create --name mslearn-mlops-my-deployment --endpoint $endpoint_name \
            -f endpoints/online/deployment.yml \
            --all-traffic \
            --resource-group $resource_group \
            --workspace-name $workspace_name

      # Step 6: Invoke the Endpoint
      - name: Invoke the Endpoint
        run: |
          az ml online-endpoint invoke --name $endpoint_name --request-file endpoints/online/sample-request.json
