ename: Deploy Model to Endpoint

on:
  push:
    branches:
      - main

jobs:
  deploy-model:
    runs-on: ubuntu-latest
    environment:
      name: prod_env

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@main

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install Azure ML CLI
      - name: Install Azure CLI Python packages
        run: |
          pip install azure-ai-ml azure-identity

      # Step 4: Install the Azure ML CLI extension
      - name: Install az ml extension
        run: az extension add -n ml -y

      # Step 5: Azure login
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      # Step 6: Deploy Model to Endpoint
      - name: Deploy Model to Endpoint
        run: |
          # Set variables
          resource_group="rg-for-mslearn-mlops"
          workspace_name="ws2-mslearn-mlops-prod" 
          endpoint_name="mslearn-mlops-my-online-endpoint"
          deployment_name="mslearn-mlops-my-deployment"
          model_name="model-from-job-output-manually-registered"
          model_version="1"

          # Check if endpoint exists and create or update accordingly
          if az ml online-endpoint show --name $endpoint_name --resource-group $resource_group --workspace-name $workspace_name; then
            az ml online-endpoint update --name $endpoint_name -f endpoints/online/endpoint.yml --resource-group $resource_group --workspace-name $workspace_name
          else
            az ml online-endpoint create --name $endpoint_name -f endpoints/online/endpoint.yml --resource-group $resource_group --workspace-name $workspace_name
          fi

          # Create the deployment
          az ml online-deployment create \
            --name $deployment_name 
            --endpoint-name $endpoint_name \
            -f endpoints/online/deployment.yaml \
            --all-traffic

          # Invoke the endpoint to validate deployment
          az ml online-endpoint invoke --name $endpoint_name --request-file endpoints/online/sample-request.json || { echo 'Endpoint invocation failed'; exit 1; }
